{{- if (.Values.prometheusRules).enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "crtsh-kubernetes.name" . }}-rules
  labels:
    {{- include "crtsh-kubernetes-service-monitor.labels" . | nindent 4 }}
    {{- include "crtsh-kubernetes.selectorLabels" . | nindent 4 }}
spec:
  groups:
  - name: CertificateExpiryAlerts
    rules:
    - alert: CertificateExpiringCritical
      expr: (crtsh_exporter_certificate_expiry - time()) < ({{ .Values.prometheusRules.criticalDays }} * 24 * 3600)
      for: 10m
      labels:
        severity: {{ .Values.prometheusRules.expiringCritical.severity }}
      annotations:
        summary: "SSL Certificate critically close to expiry"
        description: "Certificate for {{`{{`}} $labels.name {{`}}`}} will expire in less than {{ .Values.prometheusRules.expiringCritical.days }} days (expires at {{`{{`}} $value | humanizeTimestamp {{`}}`}})"

    - alert: CertificateExpiringWarning
      expr: (crtsh_exporter_certificate_expiry - time()) < ({{ .Values.prometheusRules.warningDays }} * 24 * 3600)
      for: 10m
      labels:
        severity: {{ .Values.prometheusRules.expiringWarning.severity }}
      annotations:
        summary: "SSL Certificate expiring soon"
        description: "Certificate for {{`{{`}} $labels.name {{`}}`}} will expire in less than {{ .Values.prometheusRules.expiringWarning.days }} days (expires at {{`{{`}} $value | humanizeTimestamp {{`}}`}})"

    - alert: CertificateExpiringInfo
      expr: (crtsh_exporter_certificate_expiry - time()) < ({{ .Values.prometheusRules.expiringInfo.days }} * 24 * 3600)
      for: 10m
      labels:
        severity: {{ .Values.prometheusRules.expiringInfo.severity }}
      annotations:
        summary: "SSL Certificate expiration approaching"
        description: "Certificate for {{`{{`}} $labels.name {{`}}`}} will expire in less than {{ .Values.prometheusRules.expiringInfo.days }} days (expires at {{`{{`}} $value | humanizeTimestamp {{`}}`}})"
{{- end }}