{{- if (.Values.prometheusRules).enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "crtsh-kubernetes.name" . }}-rules
  labels:
    {{- include "crtsh-kubernetes-service-monitor.labels" . | nindent 4 }}
    {{- include "crtsh-kubernetes.selectorLabels" . | nindent 4 }}
spec:
  groups:
  - name: CertificateExpiryAlerts
    rules:
    - alert: CertificateExpiringCritical
      expr: (crtsh_exporter_certificate_expiry - vector(time())) < ({{ .Values.prometheusRules.criticalDays }} * 24 * 3600)
      for: {{ .Values.prometheusRules.alert_for }}
      labels:
        severity: critical
      annotations:
        summary: "SSL Certificate critically close to expiry"
        description: "Certificate for {{`{{`}} $labels.name {{`}}`}} will expire in less than {{ .Values.prometheusRules.criticalDays }} days (expires at {{`{{`}} $value | humanizeTimestamp {{`}}`}})"

    - alert: CertificateExpiringWarning
      expr: (crtsh_exporter_certificate_expiry - vector(time())) < ({{ .Values.prometheusRules.warningDays }} * 24 * 3600)
      for: {{ .Values.prometheusRules.alert_for }}
      labels:
        severity: warning
      annotations:
        summary: "SSL Certificate expiring soon"
        description: "Certificate for {{`{{`}} $labels.name {{`}}`}} will expire in less than {{ .Values.prometheusRules.warningDays }} days (expires at {{`{{`}} $value | humanizeTimestamp {{`}}`}})"

    - alert: CertificateExpiringInfo
      expr: (crtsh_exporter_certificate_expiry - vector(time())) < ({{ .Values.prometheusRules.infoDays }} * 24 * 3600)
      for: {{ .Values.prometheusRules.alert_for }}
      labels:
        severity: info
      annotations:
        summary: "SSL Certificate expiration approaching"
        description: "Certificate for {{`{{`}} $labels.name {{`}}`}} will expire in less than {{ .Values.prometheusRules.infoDays }} days (expires at {{`{{`}} $value | humanizeTimestamp {{`}}`}})"
{{- end }}