apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "crtsh-kubernetes.name" . }}
  labels:
    {{- include "crtsh-kubernetes.labels" . | nindent 4 }}
    {{- include "crtsh-kubernetes-service-monitor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "crtsh-kubernetes.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.prometheus.scrapeInterval | default "300s" }}
      scrapeTimeout: "{{ .Values.prometheus.scrapeTimeout | default "90s" }}"