apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
  name: {{ include "crtsh-kubernetes.fullname" . }}
  labels:
    {{- include "crtsh-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crtsh-kubernetes.selectorLabels" . | nindent 4 }}
