networks:
  crtsh-exporter:
    driver: bridge

services:
  crtsh-exporter:
    image: "ghcr.io/dazwilkin/crtsh-exporter:latest"
    environment:
      TEST: "TEST"
    ports:
      - "8080:8080"
    networks:
      - crtsh-exporter
