networks:
  turbot:
    driver: bridge

services:
  steampipe:
    image: "ghcr.io/dazwilkin/crtsh-exporter:latest"
    environment:
      TEST: "TEST"
    ports:
      - "9193:9193"
    networks:
      - turbot
    healthcheck:
      test: ["CMD-SHELL", "bash ./healthcheck.sh"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s
    volumes:
      - ~/.kube/config:/home/steampipe/.kube/config  # mount kubeconfig
      - ./steampipe/init-db.sql:/home/steampipe/initdb-sql-scripts/custom-functions.sql
      - ~/.aws/credentials:/home/steampipe/.aws/credentials  # mount aws credentials
  powerpipe:
    build:
      context: ./powerpipe
      args:
        PRE_INSTALL_MODS: "github.com/turbot/steampipe-mod-kubernetes-insights github.com/turbot/steampipe-mod-kubernetes-compliance"
        POWERPIPE_BINARY_DOWNLOAD_URL: https://github.com/turbot/powerpipe/releases/download/v0.4.4/powerpipe.linux.arm64.tar.gz
    environment:
      INSTALL_MODS: "github.com/turbot/steampipe-mod-kubernetes-insights github.com/turbot/steampipe-mod-kubernetes-compliance"
      POWERPIPE_DATABASE: postgres://steampipe:abcd1234@steampipe:9193/steampipe
    ports:
      - "9033:9033"
    depends_on:
      steampipe:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "bash ./healthcheck.sh"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    networks:
      - turbot


